version: '3.5'
services:
  client:
    container_name: client_container
    build: ./client
    ports: 
      - 8080:8080
    volumes:
      - ./client:/client
      - /client/node_modules 
    entrypoint: ["sh", "./client/scripts/start.sh"]
  db:
    image: postgres
    ports:
      - "5432:5432"  
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - app-network

  api:
    restart: always
    build: ./api
    container_name: api_container
    #command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./api:/api
    depends_on:
      - db
    networks:
      - app-network
    entrypoint: ["sh","./scripts/start.sh"]


networks:
  app-network:
    external: true
      